name: PetStore Regression API Tests

on:
  workflow_dispatch:

jobs:

  regression-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Maven
        run: mvn -version

      - name: Clean Build
        run: mvn clean install

      - name: Execute Regression Tests
        run: mvn test -Dgroups=regression

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-allure-report
          path: target/site/allure-maven-plugin