name: PetStore Smoke API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:

      env:
        description: 'Environment Name'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - stg
          - prod

      group:
        description: 'Test Group'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
          - pet
          - store

jobs:

  smoke-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t petstore-framework .

      - name: Create Report Directory
        run: mkdir -p reports

      - name: Execute Tests Inside Docker
        run: |
          docker run --rm \
          -e ENV=${{ github.event.inputs.env || 'qa' }} \
          -e GROUP="-Dgroups=${{ github.event.inputs.group || 'smoke' }}" \
          -v ${{ github.workspace }}/reports:/app/target/site/allure-maven-plugin \
          petstore-framework

      - name: Set Timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.group || 'smoke' }}-${{ github.event.inputs.env || 'qa' }}-${{ env.TIMESTAMP }}
          path: reports